<a href="https://colab.research.google.com/github/hjiwoong/bigdata/blob/main/EDA_%EA%B8%B0%EC%B4%88%ED%86%B5%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#필요한 라이브러리 임포트
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [4]:
#iris 데이터셋 불러오기
iris = load_iris()

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

### pandas dataFrame

In [8]:
#데이터프레임으로 변환
df = pd.DataFrame(iris.data,columns=['sepal_length','sepal_width','petal_length','petal_width'])
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)

In [10]:
#데이터 확인
print("=== 데이터 상위 5행 ===")
print(df.head())

=== 데이터 상위 5행 ===
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
print("\n=== 데이터 형태 (행, 열) ===")
print(df.shape)

=== 데이터 형태 (행, 열) ===
(150, 5)

In [13]:
print("\n=== 칼럼 유형 확인 ===")
print(df.dtypes)

=== 칼럼 유형 확인 ===
sepal_length     float64
sepal_width      float64
petal_length     float64
petal_width      float64
species         category
dtype: object

In [18]:
print("\n===결측치 확인 ===")
print(df.isnull().sum())

===결측치 확인 ===
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [20]:
print("\n=== 종류별 데이터 개수 ===")
print(df['species'].value_counts())

=== 종류별 데이터 개수 ===
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

###평균(Mean)

In [23]:
#단일 칼럼 평균
print("꽃받침 길이 평균: ",df['sepal_length'].mean())
print(f"꽃받침 길이 평균: {df['sepal_length'].mean():.2f}")

꽃받침 길이 평균:  5.843333333333334
꽃받침 길이 평균: 5.84

In [29]:
#전체 숫자형 칼럼 평균
print("전체 칼럼 평균:")
print(df.mean(numeric_only=True).round(2))
#(numeric_only=True) 숫자형 칼럼(정수, 실수)만 계산

전체 칼럼 평균:
sepal_length    5.84
sepal_width     3.06
petal_length    3.76
petal_width     1.20
dtype: float64

In [33]:
#종류별 평균 비교
print("종류별 꽃잎 길이 평균:")
print(df.groupby('species')['petal_length'].mean())

종류별 꽃잎 길이 평균:
species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

/tmp/ipykernel_351/3258431193.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('species')['petal_length'].mean())

### 중앙값(Median)

In [35]:
#단일 칼럼 중앙값
print("꽃받침 길이 중앙값:",df['sepal_length'].median())

꽃받침 길이 중앙값: 5.8

In [42]:
#전체 칼럼 중앙값
print("전체 칼럼 중앙값:")
print(df.median(numeric_only=True))

전체 칼럼 중앙값:
sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [43]:
#평균 vs 중앙값 비교
print("=== 평균 vs 중앙값 비교 ===")
comparison = pd.DataFrame({
    '평균': df.mean(numeric_only=True).round(2),
    '중앙값': df.median(numeric_only=True)
})
print(comparison)

=== 평균 vs 중앙값 비교 ===
                평균   중앙값
sepal_length  5.84  5.80
sepal_width   3.06  3.00
petal_length  3.76  4.35
petal_width   1.20  1.30

### 최소값/최대값 (Min/Max)

In [45]:
#최소값
print("=== 최소값 ===")
print(df.min(numeric_only=True))

=== 최소값 ===
sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
dtype: float64

In [47]:
#최대값
print("=== 최대값 ===")
print(df.max(numeric_only=True))

=== 최대값 ===
sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
dtype: float64

In [49]:
#범위(최대값 - 최소값)
print("=== 범위(Range) ===")
numeric_cols = df.select_dtypes(include='number')
print(numeric_cols.max() - numeric_cols.min())
#df에서 숫자형 데이터를 포함하는 칼럼만 선택하여 새로운 DataFrame인 numeric_cols를 생성

=== 범위(Range) ===
sepal_length    3.6
sepal_width     2.4
petal_length    5.9
petal_width     2.4
dtype: float64

In [66]:
#어떤 행이 최대값/최소값인지 확인
print("꽃받침 길이가 가장 긴 꽃:")
print(df['sepal_length'].idxmax())
print(df.loc[131]) #131행의 컬럼과 값이 출력
print("\n")
print(df.loc[df['sepal_length'].idxmax()])
#.idxmax(): 'sepal_length' 칼럼에서 가장 큰 값(최대값)을 가지는 행의 인덱스를 반환
#.loc[]: 인덱서를 사용하여 특정 행 또는 칼럼을 레이블(이름)을 기반으로 선택

꽃받침 길이가 가장 긴 꽃:
131
sepal_length          7.9
sepal_width           3.8
petal_length          6.4
petal_width           2.0
species         virginica
Name: 131, dtype: object


sepal_length          7.9
sepal_width           3.8
petal_length          6.4
petal_width           2.0
species         virginica
Name: 131, dtype: object

### 분위수(Quantile/Percentile)

In [70]:
#분위수 구하기
print("=== 분위수(25%, 50%, 75%) ===")
print(df.quantile([0.25,0.5,0.75],numeric_only=True))

=== 분위수(25%, 50%, 75%) ===
      sepal_length  sepal_width  petal_length  petal_width
0.25           5.1          2.8          1.60          0.3
0.50           5.8          3.0          4.35          1.3
0.75           6.4          3.3          5.10          1.8

In [74]:
#특정 칼럼의 분위수
col = 'sepal_length'
Q1 = df[col].quantile(0.25)
Q2 = df[col].quantile(0.50)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1
print(f"꽃받침 길이 분위수: ")
print(f" Q1 (25%): {Q1}")
print(f" Q2 (50%): {Q2}")
print(f" Q3 (75%): {Q3}")
print(f" IQR: {IQR}")

꽃받침 길이 분위수:
 Q1 (25%): 5.1
 Q2 (50%): 5.8
 Q3 (75%): 6.4
 IQR: 1.3000000000000007

In [77]:
#이상치 경계값
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print("이상치 경계값:")
print(f" 하한: {lower:.2f}")
print(f" 상한: {upper:.2f}")

이상치 경계값:
 하한: 3.15
 상한: 8.35

In [84]:
#이상치 확인
outliers = df[(df[col] < lower) | (df[col] > upper)]
print(f"이상치 데이터 수: {len(outliers)}개")
#df[True, False, True] DataFrame에 불리언 시리즈를 전달하면 True로 표시된 행들만 필터링하여 새로운 DataFrame인 outliers을 반환

이상치 데이터 수: 0개

In [86]:
df[col]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [89]:
outliers

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

### 분산(Variance)

In [94]:
#단일 칼럼 분산
print("꽃받침 길이 분산:", df['sepal_length'].var())
print("\n")
print(f"꽃받침 길이 분산: {df['sepal_length'].var():.2f}")

꽃받침 길이 분산: 0.6856935123042505


꽃받침 길이 분산: 0.69

In [96]:
#전체 칼럼 분산
print("=== 전체 칼럼 분산 ===")
print(df.var(numeric_only=True).round(2))

=== 전체 칼럼 분산 ===
sepal_length    0.69
sepal_width     0.19
petal_length    3.12
petal_width     0.58
dtype: float64

In [98]:
#종류별 분산 비교(분산이 크면 데이터가 넓게 퍼져있음)
print("종류별 꽃잎 길이 분산")
print(df.groupby('species')['petal_length'].var().round(2))

종류별 꽃잎 길이 분산
species
setosa        0.03
versicolor    0.22
virginica     0.30
Name: petal_length, dtype: float64

/tmp/ipykernel_351/696160914.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('species')['petal_length'].var().round(2))

### 표준 편차 (Standard Deviation)

In [100]:
#단일 칼럼 표준편차
print("꽃받침 길이 표준편차:",df['sepal_length'].std())
print("\n")
print(f"꽃받침 길이 표준편차: {df['sepal_length'].std():.2f}")

꽃받침 길이 표준편차: 0.8280661279778629


꽃받침 길이 표준편차: 0.83

In [101]:
#전체 칼럼 표준편차
print("=== 전체 칼럼 표준편차 ===")
print(df.std(numeric_only=True).round(2))

=== 전체 칼럼 표준편차 ===
sepal_length    0.83
sepal_width     0.44
petal_length    1.77
petal_width     0.76
dtype: float64

In [103]:
#분산 vs 표준편차 비교정리
print("=== 분산 vs 표준편차 비교 ===")
summary = pd.DataFrame({
    '분산': df.var(numeric_only=True).round(4),
    '표준편차': df.std(numeric_only=True).round(4)
})
print(summary)
#표준편차(Standard Deviation): 분산의 제곱근으로 데이터가 평균으로부터 평균적으로 얼마나 떨어져있는지를 나타낸다.
#데이터의 원래 단위를 따르기 때문에 분산보다 직관적으로 이해하기 쉽다

#petal_length(꽃잎 길이): 평균으로부터 가장 넓게 퍼져있으며 데이터 포인트들이 서로 크게 다르다는 것을 의미
#sepal_width(꽃받침 너비): 데이터가 평균 주변에 가장 밀집되어 있으며 데이터 포인트들이 서로 유사하다는 것을 의미

=== 분산 vs 표준편차 비교 ===
                  분산    표준편차
sepal_length  0.6857  0.8281
sepal_width   0.1900  0.4359
petal_length  3.1163  1.7653
petal_width   0.5810  0.7622

In [107]:
#평균 ±표준편차 범위 (데이터의 약 68%가 이 범위에 속함)
col = 'sepal_length'
mean = df[col].mean()
std = df[col].std()
print("꽃받침 길이: 평균 ± 표준편차")
print(f" 평균: {mean:.2f}")
print(f" 표준편차: {std:.2f}")
print(f" 범위: {mean - std:.2f} ~ {mean + std:2f}")
count_in_range = df[(df[col] >= mean - std) & (df[col] <= mean + std)].shape[0]
#True로 표시된 행들만 필터링하여 새로운 DaraFrame인 count_in_range을 반환
#.shape[0]: 필터링된 DataFrame의 행의 개수를 반환
print(f"이 범위에 속하는 데이터: {count_in_range}개 ({count_in_range/len(df)*100:.1f}%)")

꽃받침 길이: 평균 ± 표준편차
 평균: 5.84
 표준편차: 0.83
 범위: 5.02 ~ 6.671399
이 범위에 속하는 데이터: 90개 (60.0%)

In [109]:
df[(df[col] >= mean - std) & (df[col] <= mean + std)]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
142           5.8          2.7           5.1          1.9  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[90 rows x 5 columns]

### 최빈값 (Mode)

In [110]:
#범주형 칼럼 최빈값
print("=== species 최빈값 ===")
print(df['species'].mode())

=== species 최빈값 ===
0        setosa
1    versicolor
2     virginica
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [112]:
#값별 빈도수 확인(범주형)
print("=== 품종별 빈도수 ===")
print(df['species'].value_counts())

=== 품종별 빈도수 ===
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [114]:
#숫자형 칼럼 최빈값
print("=== 꽃받침 길이 최빈값 ===")
print(df['sepal_length'].mode())

=== 꽃받침 길이 최빈값 ===
0    5.0
Name: sepal_length, dtype: float64

In [115]:
#숫자형 칼럼 값 빈도 확인
print("=== 꽃받침 길이 값 빈도 TOP 5 ===")
print(df['sepal_length'].value_counts().head(5))

=== 꽃받침 길이 값 빈도 TOP 5 ===
sepal_length
5.0    10
6.3     9
5.1     9
6.7     8
5.7     8
Name: count, dtype: int64

In [124]:
#전체 칼럼 최빈값
print("=== 전체 칼럼 최빈값 ===")
print(df.mode().iloc[0]) #첫번째 행 선택(0번 위치)

=== 전체 칼럼 최빈값 ===
sepal_length       5.0
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

### 데이터프레임에서 기술통계 한번에 구하기

In [127]:
#기본 기술 통계(숫자형 칼럼 자동 선택)
print("=== 기술통계 요약(describe) ===")
print(df.describe().round(2))

=== 기술통계 요약(describe) ===
       sepal_length  sepal_width  petal_length  petal_width
count        150.00       150.00        150.00       150.00
mean           5.84         3.06          3.76         1.20
std            0.83         0.44          1.77         0.76
min            4.30         2.00          1.00         0.10
25%            5.10         2.80          1.60         0.30
50%            5.80         3.00          4.35         1.30
75%            6.40         3.30          5.10         1.80
max            7.90         4.40          6.90         2.50

In [130]:
#범주형 포함 전체 기술 통계
print("=== 범주형 포함 기술통계 ===")
print(df.describe(include='all').round(2))
#NaN은 'Not a Number'의 줄임말, '결측값' 또는 '누락된 값'을 나타내는 데 사용

=== 범주형 포함 기술통계 ===
        sepal_length  sepal_width  petal_length  petal_width species
count         150.00       150.00        150.00       150.00     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean            5.84         3.06          3.76         1.20     NaN
std             0.83         0.44          1.77         0.76     NaN
min             4.30         2.00          1.00         0.10     NaN
25%             5.10         2.80          1.60         0.30     NaN
50%             5.80         3.00          4.35         1.30     NaN
75%             6.40         3.30          5.10         1.80     NaN
max             7.90         4.40          6.90         2.50     NaN

In [132]:
#종류별 기술 통계 (groupby + describe)
print("=== 종류별 기술통계 ===")
print(df.groupby('species').describe())

=== 종류별 기술통계 ===
           sepal_length                               ... petal_width
                  count   mean       std  min    25%  ...         min  25%  50%  75%  max
species                                               ...
setosa             50.0  5.006  0.352490  4.3  4.800  ...         0.1  0.2  0.2  0.3  0.6
versicolor         50.0  5.936  0.516171  4.9  5.600  ...         1.0  1.2  1.3  1.5  1.8
virginica          50.0  6.588  0.635880  4.9  6.225  ...         1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

/tmp/ipykernel_351/2811819381.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('species').describe())

In [134]:
#내가 원하는 통계만 선택해서 보기
print("=== 커스텀 기술 통계 ===")
custom_stats = df.groupby('species')['petal_length'].agg([
    ('평균', 'mean'),
    ('중앙', 'median'),
    ('표준편차', 'std'),
    ('최소값', 'min'),
    ('최대값', 'max')
]).round(3)
print(custom_stats)
#.add([...]): 하나 이상의 집계(aggregation) 함수를 적용하는 메서드
#('평균', 'mean'): 'mean'함수를 적용하여 평균을 계산하고, 결과 칼럼의 이름을 '평균'

=== 커스텀 기술 통계 ===
               평균    중앙   표준편차  최소값  최대값
species
setosa      1.462  1.50  0.174  1.0  1.9
versicolor  4.260  4.35  0.470  3.0  5.1
virginica   5.552  5.55  0.552  4.5  6.9

/tmp/ipykernel_351/288733999.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  custom_stats = df.groupby('species')['petal_length'].agg([